/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.bridgelabz.mathoperations;

@FunctionalInterface
interface IMathFunction {
    int calculate(int a, int b);
    static void printResult(String operation, int a, int b, IMathFunction function) {
		System.out.println(operation+" "+function.calculate(a, b));
	}
}

public class MathOperation{
    public static void main(String[] args) {
    	
        IMathFunction add = Integer::sum;
        IMathFunction multiply = (a, b) -> a * b;
        IMathFunction divide = (int a, int b) -> a / b;
        IMathFunction subtract = (int a, int b) -> a - b;
     
        IMathFunction.printResult("Addition", 1, -2, add);
		IMathFunction.printResult("Multiplication", 1, 2, multiply);
		IMathFunction.printResult("Division", 1, 2, divide);
		IMathFunction.printResult("Subtraction", 1, 2, subtract);
        
    }
}
