/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.bridgelabz.mathoperations;

@FunctionalInterface
interface IMathFunction {
    int calculate(int a, int b);
}

public class MathOperation{
    public static void main(String[] args) {
    	
        IMathFunction add = Integer::sum;
        IMathFunction multiply = (a, b) -> a * b;
        IMathFunction divide = (int a, int b) -> a / b;
        IMathFunction subtract = (int a, int b) -> a - b;
     
        System.out.println("Addition " + add.calculate(1, 2));
        System.out.println("Multiplication " + multiply.calculate(1, 2));
        System.out.println("Division " + divide.calculate(1, 2));
        System.out.println("Subtraction " + subtract.calculate(1, 2));
        
    }
}
